# Introduction {#sec:introduction}

Survey data for the Atlantic halibut (*Hippoglossus hippoglossus*) population on the Scotian Shelf were originally obtained as part of the Fisheries and Ocean's (DFO) summer Research Vessel (RV) bottom trawl survey [@DenHeyer2015]. This survey provides indices of abundance, indices of biomass, and biological samples for groundfish and other components of the ecosystem. Some commercially valuable fish and invertebrate stocks are not well sampled by trawl gear, such as halibut [@Zwanenburg2003], and alternate methods to monitor abundance are used. In the case of halibut, the Industry-DFO Halibut longline survey was initiated in 1998 using longline gear to provide indices of abundance. A fixed stations design was adopted and fishing was completed by commercial fishermen, with at-sea observers recording data on the catch by weight of target species (Atlantic halibut) and non-target species (anything else) [@Zwanenburg2000;@Trzcinski2009;@DenHeyer2015]. The aim of this new survey was to obtain information on size composition, diet, movement and bycatch species for stock assessment purposes [@Zwanenburg2000]. Initially, the stratified mean catch per hook was used as an index of abundance. In 2009, a generalized linear model was implemented to obtain standardized survey catch rates of halibut weight [@Trzcinski2009;@Smith2016a].

An extensive review of methods to estimate catch per unit effort for longline gear [@Smith2016a] concluded that catch per unit effort standardization methods ignored the presence and abundance of non-target species and both intra- and inter-species competition for hooks. A multivariate Multinomial Exponential Model (MEM) originally developed by @Rothschild1967 and later reformulated by @Etienne2013 was recommended. The switch to this model required hook condition data, such as the number of baited and unbaited hooks, in addition to total numbers of target and non-target species caught [@Smith2016a]. In 2017, a new stratified random survey was established with more standardized protocols and strata that encompassed the entire management unit [@DFO2021]. To obtain the data for the MEM model, this new survey also required the collection of hook condition data. To calibrate the new stratified random survey, a subset of fixed station sets have also been completed to provide the opportunity to calibrate the surveys.

While the MEM showed great promise and could easily be modified to incorporate covariates [@Smith2016a], its original formulation could not account for any spatial patterns in catch rates [@Luo2022] which are likely to exist due to the scale and environmental complexity of the Atlantic halibut management areas [@Shackell2021]. Recent work utilizing geostatistics was able to harness this previously ignored information to obtain improved estimates of both station-specific and overall catch rates [@Luo2022]. However, this work focused exclusively on the data from the stratified random sampling design (2017 onwards), leaving 19 years of data unused. Given the importance of this survey for halibut management, the Atlantic Halibut Council sponsored the extension of this strictly spatial approach to a fully spatio-temporal model that could include data from both surveys to provide an index from 1998 to the present. The Term of Reference for this work (including the agreed-upon deliverables) are provided in Appendix 1. This report aims to present a fully spatio-temporal MEM and a comparative analysis when utilizing data from the Scotian Shelf and the Southern Grand Banks (NAFO divisions 3NOP4VWX) on the eastern coast of Canada. It further aims to assess the ability of only the fixed stations data to account for temporal changes in the abundance of Atlantic halibut.



