# Discussion

This novel spatio-temporal MEM is able to successfully capture the changes of the halibut distribution and abundance over time and space for all available data with the exception of the first two years, including two different survey designs. It is the only model examined within that is able to include all this information in a unified framework while extracting the maximum amount of information from the available data as possible. Furthermore, since this model is able to output both station-specific estimated catch rate and an overall estimated catch rate for the entire region, it both increases the amount of information available to manage this fishery while being directly comparable to current methods utilized to obtain an index of abundance.

The halibut stock assessment model requires indices of biomass instead of numbers of fish caught or catch rates [@Trzcinski2016;Cox2018], meaning that the estimated catch rates from this model cannot be directly utilized by the assessment model. As the dataset contain average fish weight by set, it is a potential transformation away from having catch rates in biomass per hook per minute instead of in number of fish, which are then much more applicable and can still retain and propagate uncertainties forward through the delta method [@Bickel2015]. However, more work is necessary to be able to obtain the biomass output as stations that did not catch any halibut will still have an expected catch rate (albeit extremely low), but no fish weight associated with it, meaning that thought has to be put into how one would transform these low catch rates into biomass.

Similarly to previous versions of the MEM, our spatio-temporal MEM and our analysis of its performance on the Atlantic halibut fishery emphasizes the importance of accounting for the abundance of non-target species for a multivariate approach. The inability to estimate the probability of non-target escapes without hook condition information, illustrated very well in the fits that do not include the stratified dataset, demonstrates this impact very well. This underlines the importance of having a reliable estimate of the abundance of these non-target species. The modelling output themselves show that overestimating the abundance of these non-target species will likely result in an underestimation of the halibut population abundance. On the flip side, underestimating their abundance would likely result in the opposite, and completely ignoring them is likely to result in unpredictable and variable biases.

**An interesting outcome of this analysis is that there is some evidence that, while the fixed stations were likely appropriate to capture the large changes of halibut abundance, they are likely not capturing changes in distribution and abundance of non-target species in recent years which would subsequently impact the estimation of halibut abundance. The persistence analysis on its own provides only relatively weak evidence due to having a high number of pairwise comparisons and because of the fact that the number of fixed stations dropped by a third in 2017, both which could be impacting the ability of the fixed stations to track the distribution of non-target species. However, because the intercepts obtained from the model when using only the fixed stations stay consistent but spike when using the stratified random stations, a change in the distribution of non-target species that would not have been captured by the fixed station design cannot be completely rejected. As the longline gear catches a great number of other species (e.g., cod, dogfish, etc.), it is not too surprising that their overall joint spatial distribution might shift which would then have an impact on the halibut catch rates. No matter if the true reason for the change is a shift in abundance or a drop in the number of fixed stations, the proportion of the catch that is non-target increased with the new stratified survey design in 2017. It is fortunate that with the implementation of this new design additional data on hook condition is collected such that this new model model could be fit to more accurately estimate halibut abundance. Furthermore, the estimates from the stratified random design will only get more accurate and precise as years are added to the time series.**

While the spatio-temporal MEM was developed for this specific longline survey, it could easily be applied to any longline fisheries or other passive sampling gear that would be impacted by hook or bait competition and promises to improve indices of abundance used for stock assessment models. For multi-species fisheries, the spatio-temporal MEM could be of great value to further modify the multinomial equation used by our approach to expand on the non-target species to include multiple specific species. More specifically, if there are a finite amount of other species being caught aside from the target, it would likely lead to improvements in estimated catch rates for the target species.

# Acknowledgements

We want to thank the Atlantic Halibut Council for supporting this work, as well as survey coordinators, captains, crews and at-sea observers that have worked on the joint DFO-Industry survey without which none of this work would have been possible. We also thank Brendan Wringe for support on the original MEMSpa, and Jiaxin Luo for her creation of the original MEMSpa and for her help through code sharing and earlier exploration of the data. Finally, we would also like to thank both reviewers for helpful and constructive comments that helped improve this manuscript significantly.
