---
title: "Formulating a spatio-temporal model to analyze longline survey data for the Atlantic Halibut fishery"
year: 2022
report_number: nnn
author: |
  Raphaël R. McDonald^1^,
  Brad Hubley^2^,
  Lingbo Li^2^,
  Cornelia E. den Heyer^2^,
  and Joanna Mills Flemming^1^
author_list: "McDonald, R.R., Hubley, B., Li, L., den Heyer, C.E., and Mills Flemming, J."
region: Maritimes Region
isbn: ""
address: |
  ^1^Department of Mathematics and Statistics\
     Dalhousie University, 6299 South Street\
     Halifax, Nova Scotia, B3H 4R2, Canada\
  ^2^Science Branch, Maritimes Region\
    Fisheries and Oceans Canada\
    Bedford Institute of Oceanography\
    1 Challenger Drive, PO Box 1006\
    Dartmouth, NS, B2Y 4A2
phone: ""
author_footnote: "Email: raphael.mcdonald@dfo-mpo.gc.ca, rp732243@dal.ca | telephone: (581) 307-7013"
abstract: |
  The Industry-DFO Atlantic halibut (*Hippoglossus hippoglossus*) longline survey has been running since 1998 (using a fixed stations design) with the aim of providing a reliable index of halibut abundance. A 2016 review of modelling approaches recommended the use of a multinomial exponential model (MEM) to account for hook competition and the abundance of non-target species and further prompted the modification of the sampling design. Consequently, a new stratified random survey was initiated in 2017. Since then, this new stratified survey was run in parallel with the fixed station survey, but with a reduced number of fixed stations. The new survey has more standardized fishing protocols and additional hook condition data are collected to inform the MEM. The aim of this report is to present a new spatio-temporal version of MEM that is able to successfully model data from both the fixed stations and the stratified random sampling design within a unified framework. It also incorporates additional fixed and random effects, where the random effects account for the among-group variability associated with fishing vessels. The analysis further demonstrates the potential bias in abundance estimates associated with modelling changes in halibut and non-target distributions and abundance over time that would occur using the fixed stations design. It furthers shows that the switch to a stratified random sampling design was very timely and helped better quantify the increase in halibut catch rates observed since 2017.
abstract_other: |
  MUST REDO THIS SINCE MODIFIED ENGLISH ONELe relevé à la palangre de l'industrie et du MPO pour le flétan atlantique (*Hippoglossus hippoglossus*) est en cours depuis 1998 utilisant des stations fixes de collection de données et ayant comme objectif d'obtenir de l'information plus approprié sur l'abondance du flétan. Un examen des modèles utilisés sur ces données a recommandé l'utilisation d'un modèle multinomiale exponentiel (MME) capable de prendre en compte la compétition pour les crochets de pêche et l'abondance des espèces cibles et non cibles. De plus, cet examen a incité la modification du protocole de collection de données avec l'implémentation d'un plan d'échantillonage aléatoire stratifié en 2017 concurrent avec le plan d'échantillonage de stations fixes dont le nombre de stations a été réduit. Ce nouveau protocol d'échantillonage a des protocoles de pêche plus standardizé et recueille plus d'information sur la condition des crochets pour informer le MME. L'objectif principal de ce rapport est la présentation d'une nouvelle version spatio-temporelle du MME. Cette nouvelle version est capable de modèler les données provenant des stations fixes et de l'échantillonage aléatoire stratifié séparemment et ensemble, ce qui permet l'inclusion de la majorité de l'information disponible à l'intérieur du même modèle. L'analyse souligne des problèmes potentiels provenant du relevé d'échantillonage utilisant des stations fixes et démontre que l'implémentation du relevé d'échantillonage aléatoire stratifié fut opportun car il a permis au modèle de mieux capturer l'augmentation des taux de captures de flétan en 2017.
output:
 csasdown::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: false
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: false
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/library.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(# Prevent xtable from adding a timestamp comment to the table code it produces
        xtable.comment = FALSE,
        # Don't allow kableExtra to load packages, we add them manually in csasdown
        kableExtra.latex.load_packages = FALSE,
        # Stop chunk output (echo) running into the margins
        width = 80,
        # Don't use scientific notation (stops tables from showing 1.2e3, etc.)
        scipen = 999)
```

```{r load-libraries, cache=FALSE}
meta <- rmarkdown::metadata$output
if (is.null(meta)) {
  # This knitr chunk has been run in R without running bookdown::render_book("index.Rmd")
  # so rmarkdown::metadata$output is not populated
  options(french = FALSE)
} else {
  if (length(grep("pdf", names(meta)))) {
    options(french = meta$`csasdown::techreport_pdf`$french)
    prepub <- meta$`csasdown::techreport_pdf`$prepub
  } else if (length(grep("word", names(meta)))) {
    options(french = meta$`csasdown::techreport_word`$french)
    prepub <- meta$`csasdown::techreport_word`$prepub
  }
}
csl <- "csl/csas.csl"
if (is.null(getOption("french"))) {
  stop("`french` was not set up correctly in YAML header in index.Rmd. ",
       "It must be true or false",
       call. = FALSE)
}
if (getOption("french")) {
  csl <- "csl/csas-french.csl"
  options(OutDec = ",")
}

# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
```

---
csl: `r csl`    
---
