---
title: "Tech Report Model Fits (Fixed Stations)"
author: "Raphaël McDonald"
date: "8/10/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r initial-data-vis}
library(dplyr)
library(sf)

library(TMB) 


fixed_data<-read.csv("FixedSurvey_anon.csv")
dim(fixed_data)
unique(fixed_data$YEAR)
#contains a lot more data, all the way from 1998 to 2021, meaning I have twice the data for 2017-2021
colnames(fixed_data)

#The fixed data station does not appear to have the 300 hooks subset, that it is just the overall stuff from the 1000 hooks, meaning only the reduced multinomial model could be applied to it (once I've figured out the impact of a fixed survey design on the spatial model)

library(sp)
library(maptools)
library(rgeos)
library(PBSmapping)
library(ggplot2)

prj4s=CRS("+init=epsg:4326")
utm.prj4s=CRS("+init=epsg:32620")

sf_fixed_data<-st_as_sf(fixed_data, coords=c("LONGITUDE","LATITUDE"))
st_crs(sf_fixed_data)<-prj4s

survey_strats<-load("SurveyStrata_anon.RData")
survey_stret<-as.PolySet(surveyStrataPolyLL)
sp_survey_strata_poly<-PolySet2SpatialPolygons(survey_stret)
sp_survey_strata_poly@proj4string<-prj4s
for(j in 1:15){
  for(i in 1:length(sp_survey_strata_poly@polygons[[j]]@Polygons)){
    if (sp_survey_strata_poly@polygons[[j]]@Polygons[[i]]@hole==F) {
    sp_survey_strata_poly@polygons[[j]]@Polygons[[i]]@hole<-T
  }
  if (sp_survey_strata_poly@polygons[[j]]@Polygons[[i]]@hole==T) {
    sp_survey_strata_poly@polygons[[j]]@Polygons[[i]]@hole<-F
  }
}
}

sf_survey_strata_poly<-st_as_sf(sp_survey_strata_poly)

#First, make a dataframe of number of tows a year before I remove sets that are bad
n_frame<-data.frame(Year=c(1998:2021),n=rep(NA,length(1998:2021)))

for (i in 1:nrow(n_frame)){
  n_frame$n[i]<-length(fixed_data$YEAR[fixed_data$YEAR==n_frame$Year[i]])
}

#Now check for sets to be removed because they make no sense

which(is.na(fixed_data$NUM_HOOK_HAUL))
#These 9 tows have NA for how many hooks were hauled, which makes no sense, and every single one of them, from 2 NAFO areas (4XN and 4WL), all different stations, but all from a single trip in 2009 (J09-0308)

fixed_data2<-fixed_data[-which(is.na(fixed_data$NUM_HOOK_HAUL)),]

#Check if the numbers don't make sense, i.e. there are more species caught than number of hooks
which(fixed_data2$NUM_HOOK_HAUL-fixed_data2$total_other_species-fixed_data2$total_target_species<0)
#Mostly different years or trips, so no trends
fixed_data3<-fixed_data2[-which(fixed_data2$NUM_HOOK_HAUL-fixed_data2$total_other_species-fixed_data2$total_target_species<0),]

#Put together the number of empty hooks (including baited, unbaited, broken or missing hooks)
fixed_data3$empty_hooks<-fixed_data3$NUM_HOOK_HAUL-fixed_data3$total_other_species-fixed_data3$total_target_species

#Some tows have what I feel is an unreasonably small amount of empty hooks, might be worth taking a peek into it as a verification measure at some point, but I have no reason to move forward from that

#There is a problem with 1999, so gotta look into it
fixed_99<-subset(fixed_data3,YEAR==1999)
#It is the year with the 6 hook thing, I am going to remove this one and see if it works afterward

#Getting closer but still not working
fixed_data3<-fixed_data3[-which(fixed_data3$empty_hooks==6),]
# fixed_data3<-fixed_data3[-which(fixed_data3$empty_hooks==195),]

sf_rem_fix_data<-st_as_sf(fixed_data3,coords=c("LONGITUDE","LATITUDE"))
st_crs(sf_rem_fix_data)<-prj4s
#Make into utm
sf_rem_fix_data<-st_transform(sf_rem_fix_data,utm.prj4s)
sf_rem_fix_data<-sf_rem_fix_data[-c(29:33),]

#Lets try removing 1998-1999, see what happens
sf_rem_fix_data<-subset(sf_rem_fix_data,YEAR > 1999)

#Now there are a few where soak time is NA, so have to remove those
sf_rem_fix_data<-sf_rem_fix_data[-which(is.na(sf_rem_fix_data$SOAKMINP3P1)),]

for (i in 1:nrow(n_frame)){
  n_frame$fix_n[i]<-length(sf_rem_fix_data$YEAR[sf_rem_fix_data$YEAR==n_frame$Year[i]])
}

# Logit function
logitp=function(p){log(p/(1-p))}
# Inverse logist function
logitpi=function(t){exp(t)/(1+exp(t))}


dat_list_for_comb<-list()
for (i in 2000:2021){
  dat_list_for_comb[[i-1999]]<-subset(sf_rem_fix_data,YEAR==i)
}

```

```{r more-setup}
n_fixed<-nrow(sf_rem_fix_data)

vess_id<-rep(NA,n_fixed)

n_t<-length(2000:2021)
n_k<-3

main_n<-rep(NA,n_t)
for (i in 1:n_t){
  if (i<18) main_n[i]<-n_frame$fix_n[i+2]
  else main_n[i]<-n_frame$fix_n[i+2]
}

sub_n_frame<-n_frame[-c(1,2),]

Yearly_indices<-data.frame(year=c(2000:2021),
                           ind_1=c(1,217,407,606,794,1009,1173,1336,1577,1858,2063,2278,2495,2712,2945,3177,3409,3636,3734,3834,3932,4031),
                           ind_2=c(216,406,605,793,1008,1172,1335,1576,1857,2062,2277,2494,2711,2944,3176,3408,3635,3733,3833,3931,4030,4128))
ind1<-Yearly_indices$ind_1
ind2<-Yearly_indices$ind_2

soaky<-rep(NA,sum(main_n))

locations<-matrix(nrow=sum(main_n),ncol=2)

big_A<-matrix(nrow=sum(main_n),ncol=n_k)
for (i in 2000:2021){
    big_A[c((ind1[i-1999]):ind2[i-1999]),]<-as.matrix(data.frame(dat_list_for_comb[[i-1999]]$total_target_species,dat_list_for_comb[[i-1999]]$total_other_species,dat_list_for_comb[[i-1999]]$empty_hooks))
    vess_id[c((ind1[i-1999]):ind2[i-1999])]<-dat_list_for_comb[[i-1999]]$Vess_fact
    soaky[c((ind1[i-1999]):ind2[i-1999])]<-dat_list_for_comb[[i-1999]]$SOAKMINP3P1
    locations[c((ind1[i-1999]):ind2[i-1999]),]<-st_coordinates(dat_list_for_comb[[i-1999]])
}
vess_id<-as.integer(as.factor(vess_id))
vess_id<-vess_id-1

spool<-sqrt(((length(locations[,1])-1)*var(locations[,1])+(length(locations[,2])-1)*var(locations[,2]))/(length(locations[,1])+length(locations[,2])))
locations[,1]<-(locations[,1]-median(locations[,1]))/spool
locations[,2]<-(locations[,2]-median(locations[,2]))/spool

data<-list(A=big_A,vess_id=vess_id,s=soaky,locations=locations,n_t=n_t,n=main_n,n_k=3)

par_list<-list()
    
# Initial values for lambda.t, lambda.nt and pnt
# Use the estimated values as the starting points
par_list$betat = -12
par_list$betant = -8
# par_list$theta = logitp(0.8795768)
par_list$theta = 0
#Random effect of time
par_list$rand_t = rep(-12,data$n_t)
par_list$rand_nt = rep(-8,data$n_t)
# Random field
par_list$omegat =  rep(0,nrow(big_A))
par_list$omegant =  rep(0,nrow(big_A))
#Vessel effect
par_list$vess_eff_t = rep(0,length(unique(vess_id)))
par_list$vess_eff_nt = rep(0,length(unique(vess_id)))
# par_list$vess_eff_t = rep(0,length(unique(ident_fact)))
# par_list$vess_eff_nt = rep(0,length(unique(ident_fact)))
# Smoothness parameter 
par_list$lognut = 0
par_list$lognunt = 0
# Range parameter 
# par_list$logPhit = -3
# par_list$logPhint = -1
par_list$logPhit = -1
par_list$logPhint = -1
# Variance
par_list$logSigmat = 0
par_list$logSigmant = 0
#Vess effect sigmas
par_list$log_sigma_vess_t = 0
par_list$log_sigma_vess_nt = 0
#Rand intercept sigmas
par_list$log_sigma_rand_t = 0
par_list$log_sigma_rand_nt = 0
#Rand intercept means
par_list$mean_rand_t = -12
par_list$mean_rand_nt = -8
par_list$mean_ar_t = -12
par_list$mean_ar_nt = -8

par_list$logit_phi_ar_t= 0
par_list$logit_phi_ar_nt = 0

map<-list(lognut=factor(NA),lognunt=factor(NA))

random<-c("omegat","omegant","rand_t","rand_nt","vess_eff_t","vess_eff_nt")
library(optimr)

non_r<-names(par_list)[-which(names(par_list) %in% random)]

```

```{r fits-full-length}
#Fitting full dataset to all 4 fits of interest

compile("spat_temp_both_datasets_fixed.cpp")
dyn.load(dynlib("spat_temp_both_datasets_fixed"))

obj_walk<-MakeADFun(data,par_list,random=random,DLL="spat_temp_both_datasets_fixed",map=map,silent=F)
Opt_walk<-optimx::optimr(obj_walk$par,obj_walk$fn,obj_walk$gr,control=list(maxit=100000),method="nlminb")
if (Opt_walk$message=="iteration limit reached without convergence (10)") {
      obj_walk$par<-obj_walk$env$last.par[which(names(obj_walk$env$last.par) %in% non_r)]
      Opt_walk <- try(optimx::optimr(obj_walk$par,obj_walk$fn,obj_walk$gr,control=control,method="nlminb"),T)
    }
rep_walk<-sdreport(obj_walk)
Report_walk<-obj_walk$report()

save(obj_walk,Opt_walk,rep_walk,Report_walk,file="rand_walk_output_fixed.RData")

dyn.unload(dynlib("spat_temp_both_datasets_fixed"))
compile("spat_temp_mean_fixed.cpp")
dyn.load(dynlib("spat_temp_mean_fixed"))

obj_mean<-MakeADFun(data,par_list,random=random,DLL="spat_temp_mean_fixed",map=map,silent=F)
Opt_mean<-optimx::optimr(obj_mean$par,obj_mean$fn,obj_mean$gr,control=list(maxit=100000),method="nlminb")
if (Opt_mean$message=="iteration limit reached without convergence (10)") {
      obj_mean$par<-obj_mean$env$last.par[which(names(obj_mean$env$last.par) %in% non_r)]
      Opt_mean <- try(optimx::optimr(obj_mean$par,obj_mean$fn,obj_mean$gr,control=control,method="nlminb"),T)
    }
rep_mean<-sdreport(obj_mean)
Report_mean<-obj_mean$report()

save(obj_mean,Opt_mean,rep_mean,Report_mean,file="rand_mean_output_fixed.RData")

dyn.unload(dynlib("spat_temp_mean_fixed"))
compile("spat_temp_slope_fixed.cpp")
dyn.load(dynlib("spat_temp_slope_fixed"))

par_list$rand_t = rep(0,data$n_t)
par_list$rand_nt = rep(0,data$n_t)

obj_slope<-MakeADFun(data,par_list,random=random,DLL="spat_temp_slope_fixed",map=map,silent=F)
Opt_slope<-optimx::optimr(obj_slope$par,obj_slope$fn,obj_slope$gr,control=list(maxit=100000),method="nlminb")
if (Opt_slope$message=="iteration limit reached without convergence (10)") {
      obj_slope$par<-obj_slope$env$last.par[which(names(obj_slope$env$last.par) %in% non_r)]
      Opt_slope <- try(optimx::optimr(obj_slope$par,obj_slope$fn,obj_slope$gr,control=control,method="nlminb"),T)
    }
rep_slope<-sdreport(obj_slope)
Report_slope<-obj_slope$report()

save(obj_slope,Opt_slope,rep_slope,Report_slope,file="rand_slope_output_fixed.RData")

dyn.unload(dynlib("spat_temp_slope_fixed"))
compile("spat_temp_AR1_fixed.cpp")
dyn.load(dynlib("spat_temp_AR1_fixed"))

par_list$rand_t = rep(-12,data$n_t)
par_list$rand_nt = rep(-8,data$n_t)

obj_AR1<-MakeADFun(data,par_list,random=random,DLL="spat_temp_AR1_fixed",map=map,silent=F)
Opt_AR1<-optimx::optimr(obj_AR1$par,obj_AR1$fn,obj_AR1$gr,control=list(maxit=100000),method="nlminb")
if (Opt_AR1$message=="iteration limit reached without convergence (10)") {
      obj_AR1$par<-obj_AR1$env$last.par[which(names(obj_AR1$env$last.par) %in% non_r)]
      Opt_AR1 <- try(optimx::optimr(obj_AR1$par,obj_AR1$fn,obj_AR1$gr,control=control,method="nlminb"),T)
    }
rep_AR1<-sdreport(obj_AR1)
Report_AR1<-obj_AR1$report()

save(obj_AR1,Opt_AR1,rep_AR1,Report_AR1,file="rand_AR1_output_fixed.RData")

dyn.unload(dynlib("spat_temp_AR1_fixed"))

```


```{r setup2}
n_fixed<-nrow(subset(sf_rem_fix_data,YEAR>2016))

vess_id<-rep(NA,n_fixed)

n_t<-length(2017:2021)
n_k<-3

main_n<-rep(NA,n_t)
for (i in 1:n_t){
  main_n[i]<-n_frame$fix_n[i+19]
}

Yearly_indices<-data.frame(year=c(2017:2021),
                           ind_1=c(1,99,199,297,396),
                           ind_2=c(98,198,296,395,493))
ind1<-Yearly_indices$ind_1
ind2<-Yearly_indices$ind_2

soaky<-rep(NA,sum(main_n))

locations<-matrix(nrow=sum(main_n),ncol=2)

big_A<-matrix(nrow=sum(main_n),ncol=n_k)
for (i in 2017:2021){
    big_A[c((ind1[i-2016]):ind2[i-2016]),]<-as.matrix(data.frame(dat_list_for_comb[[i-1999]]$total_target_species,dat_list_for_comb[[i-1999]]$total_other_species,dat_list_for_comb[[i-1999]]$empty_hooks))
    vess_id[c((ind1[i-2016]):ind2[i-2016])]<-dat_list_for_comb[[i-1999]]$Vess_fact
    soaky[c((ind1[i-2016]):ind2[i-2016])]<-dat_list_for_comb[[i-1999]]$SOAKMINP3P1
    locations[c((ind1[i-2016]):ind2[i-2016]),]<-st_coordinates(dat_list_for_comb[[i-1999]])
}

vess_id<-as.numeric(as.factor(vess_id))-1

spool<-sqrt(((length(locations[,1])-1)*var(locations[,1])+(length(locations[,2])-1)*var(locations[,2]))/(length(locations[,1])+length(locations[,2])))
locations[,1]<-(locations[,1]-median(locations[,1]))/spool
locations[,2]<-(locations[,2]-median(locations[,2]))/spool

data<-list(A=big_A,vess_id=vess_id,s=soaky,locations=locations,n_t=n_t,n=main_n,n_k=3)

par_list<-list()
    
# Initial values for lambda.t, lambda.nt and pnt
# Use the estimated values as the starting points
par_list$betat = -12
par_list$betant = -8
# par_list$theta = logitp(0.8795768)
par_list$theta = 0
#Random effect of time
par_list$rand_t = rep(-12,data$n_t)
par_list$rand_nt = rep(-8,data$n_t)
# Random field
par_list$omegat =  rep(0,nrow(big_A))
par_list$omegant =  rep(0,nrow(big_A))
#Vessel effect
par_list$vess_eff_t = rep(0,length(unique(vess_id)))
par_list$vess_eff_nt = rep(0,length(unique(vess_id)))
# par_list$vess_eff_t = rep(0,length(unique(ident_fact)))
# par_list$vess_eff_nt = rep(0,length(unique(ident_fact)))
# Smoothness parameter 
par_list$lognut = 0
par_list$lognunt = 0
# Range parameter 
# par_list$logPhit = -3
# par_list$logPhint = -1
par_list$logPhit = -1
par_list$logPhint = -1
# Variance
par_list$logSigmat = 0
par_list$logSigmant = 0
#Vess effect sigmas
par_list$log_sigma_vess_t = 0
par_list$log_sigma_vess_nt = 0
#Rand intercept sigmas
par_list$log_sigma_rand_t = 0
par_list$log_sigma_rand_nt = 0
#Rand intercept means
par_list$mean_rand_t = -12
par_list$mean_rand_nt = -8
par_list$mean_ar_t = -12
par_list$mean_ar_nt = -8

par_list$logit_phi_ar_t= 0
par_list$logit_phi_ar_nt = 0

map<-list(lognut=factor(NA),lognunt=factor(NA))

random<-c("omegat","omegant","rand_t","rand_nt","vess_eff_t","vess_eff_nt")
library(optimr)

non_r<-names(par_list)[-which(names(par_list) %in% random)]
```


```{r fits-full-length-2017}
#Fitting full dataset to all 4 fits of interest

compile("spat_temp_both_datasets_fixed.cpp")
dyn.load(dynlib("spat_temp_both_datasets_fixed"))

obj_walk<-MakeADFun(data,par_list,random=random,DLL="spat_temp_both_datasets_fixed",map=map,silent=F)
Opt_walk<-optimx::optimr(obj_walk$par,obj_walk$fn,obj_walk$gr,control=list(maxit=100000),method="nlminb")
if (Opt_walk$message=="iteration limit reached without convergence (10)") {
      obj_walk$par<-obj_walk$env$last.par[which(names(obj_walk$env$last.par) %in% non_r)]
      Opt_walk <- try(optimx::optimr(obj_walk$par,obj_walk$fn,obj_walk$gr,control=control,method="nlminb"),T)
    }
rep_walk<-sdreport(obj_walk)
Report_walk<-obj_walk$report()

save(obj_walk,Opt_walk,rep_walk,Report_walk,file="rand_walk_output_fixed_2017.RData")

dyn.unload(dynlib("spat_temp_both_datasets_fixed"))
compile("spat_temp_mean_fixed.cpp")
dyn.load(dynlib("spat_temp_mean_fixed"))

obj_mean<-MakeADFun(data,par_list,random=random,DLL="spat_temp_mean_fixed",map=map,silent=F)
Opt_mean<-optimx::optimr(obj_mean$par,obj_mean$fn,obj_mean$gr,control=list(maxit=100000),method="nlminb")
if (Opt_mean$message=="iteration limit reached without convergence (10)") {
      obj_mean$par<-obj_mean$env$last.par[which(names(obj_mean$env$last.par) %in% non_r)]
      Opt_mean <- try(optimx::optimr(obj_mean$par,obj_mean$fn,obj_mean$gr,control=control,method="nlminb"),T)
    }
rep_mean<-sdreport(obj_mean)
Report_mean<-obj_mean$report()

save(obj_mean,Opt_mean,rep_mean,Report_mean,file="rand_mean_output_fixed_2017.RData")

dyn.unload(dynlib("spat_temp_mean_fixed"))
compile("spat_temp_slope_fixed.cpp")
dyn.load(dynlib("spat_temp_slope_fixed"))

par_list$rand_t = rep(0,data$n_t)
par_list$rand_nt = rep(0,data$n_t)

obj_slope<-MakeADFun(data,par_list,random=random,DLL="spat_temp_slope_fixed",map=map,silent=F)
Opt_slope<-optimx::optimr(obj_slope$par,obj_slope$fn,obj_slope$gr,control=list(maxit=100000),method="nlminb")
if (Opt_slope$message=="iteration limit reached without convergence (10)") {
      obj_slope$par<-obj_slope$env$last.par[which(names(obj_slope$env$last.par) %in% non_r)]
      Opt_slope <- try(optimx::optimr(obj_slope$par,obj_slope$fn,obj_slope$gr,control=control,method="nlminb"),T)
    }
rep_slope<-sdreport(obj_slope)
Report_slope<-obj_slope$report()

save(obj_slope,Opt_slope,rep_slope,Report_slope,file="rand_slope_output_fixed_2017.RData")

dyn.unload(dynlib("spat_temp_slope_fixed"))
compile("spat_temp_AR1_fixed.cpp")
dyn.load(dynlib("spat_temp_AR1_fixed"))

par_list$rand_t = rep(-12,data$n_t)
par_list$rand_nt = rep(-8,data$n_t)

obj_AR1<-MakeADFun(data,par_list,random=random,DLL="spat_temp_AR1_fixed",map=map,silent=F)
Opt_AR1<-optimx::optimr(obj_AR1$par,obj_AR1$fn,obj_AR1$gr,control=list(maxit=100000),method="nlminb")
if (Opt_AR1$message=="iteration limit reached without convergence (10)") {
      obj_AR1$par<-obj_AR1$env$last.par[which(names(obj_AR1$env$last.par) %in% non_r)]
      Opt_AR1 <- try(optimx::optimr(obj_AR1$par,obj_AR1$fn,obj_AR1$gr,control=control,method="nlminb"),T)
    }
rep_AR1<-sdreport(obj_AR1)
Report_AR1<-obj_AR1$report()

save(obj_AR1,Opt_AR1,rep_AR1,Report_AR1,file="rand_AR1_output_fixed_2017.RData")

dyn.unload(dynlib("spat_temp_AR1_fixed"))

```

